export {default as LelouchAvater} from './lelouch lamperouge.avif'
export {default as KallenStadtfeldAvater} from './Kallen Stadtfeld.jpg'
export {default as NunnallyAvater} from './Nunnally.webp'
export {default as C2Avater} from './C2.webp'
export {default as ShirleyFenetteAvater} from './Shirleyfenette.webp'
export {default as SuzakuKururugiAvater} from './Suzaku Kururugi.webp'
export {default as about} from './about.webp'
export {default as about01} from './about01.png'
export {default as about02} from './about02.png'
export {default as about03} from './about03.png'
export {default as about04} from './about04.png'
export {default as hackerman} from './hackerman.png'
