export {default as About} from './about/About'
export {default as Contact} from './contact/Contact'
export {default as Experience} from './experience/Experience'
export {default as Footer} from './footer/Footer'
export {default as Header} from './header/Header'
export {default as NavBar} from './nav/Nav'
export {default as Testimonial} from './testimonial/Testimonial'
export {default as Portfolio} from './portfolio/Portfolio'