name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        npm install
        npm run-script build
      env:
        REACT_APP_EMAIL_SERVICE: ${{ secrets.REACT_APP_EMAIL_SERVICE }}
        REACT_APP_EMAIL_TEMPLETE: ${{ secrets.REACT_APP_EMAIL_TEMPLETE }}
        REACT_APP_USER_ID: ${{ secrets.REACT_APP_USER_ID }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
